# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180817_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategori',
            field=models.CharField(default='asker', max_length=120, verbose_name='Kategori(Eğitim/Yazı)'),
            preserve_default=False,
        ),
    ]
