# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='TSK, Sağlık yönetmeliği, Tsk sağlık yönetmeliği', max_length=300, verbose_name='Taglar , ile ayır'),
            preserve_default=False,
        ),
    ]
