# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='https://www.youtube.com/watch?v=ZjkmVOc_6oA', max_length=420, verbose_name='Video link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='kategori',
            field=models.CharField(max_length=120, verbose_name='Kategori(Eğitim/Yazı/video)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, editable=False, verbose_name='like'),
        ),
        migrations.AlterField(
            model_name='post',
            name='look',
            field=models.IntegerField(default=0, editable=False, verbose_name='like'),
        ),
    ]
