# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-01 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20180901_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
