# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosya',
            name='metin',
            field=models.CharField(default='yes', max_length=460, verbose_name='Özeti'),
            preserve_default=False,
        ),
    ]
