# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-19 10:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0002_dosya_metin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='metin',
            field=ckeditor.fields.RichTextField(max_length=460, verbose_name='Özeti'),
        ),
    ]
