# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-19 10:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=195, verbose_name='Başlık')),
                ('mail', models.CharField(max_length=195, verbose_name='e-mail')),
                ('konu', models.CharField(max_length=195, verbose_name='Konu')),
                ('mesaj', ckeditor.fields.RichTextField(verbose_name='Mesaj')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('comment', models.IntegerField(default=1, editable=False, verbose_name='like')),
            ],
            options={
                'ordering': ['-tarih', '-id'],
            },
        ),
    ]
