# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-19 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iletisim',
            name='completed',
            field=models.BooleanField(default=True, verbose_name='Durum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iletisim',
            name='isim',
            field=models.CharField(max_length=195, verbose_name='İsim'),
        ),
    ]
