# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0002_auto_20180819_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisim',
            name='completed',
            field=models.BooleanField(default='False', verbose_name='Durum'),
        ),
    ]
