# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-19 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20180817_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='abone',
            name='status',
            field=models.BooleanField(default='False', verbose_name='Durum'),
        ),
    ]
